services:
  - type: web
    name: twig-ticket-manager
    env: php
    buildCommand: |
      npm install
      npm run build:css
      composer install
    startCommand: php -S 0.0.0.0:10000 -t public
